tywalch/electrodb

- package.json
- src/clauses.js
- src/entity.js
- src/errors.js
- test/offline.entity.spec.js
- test/offline.options.spec.js
The query option `table` was not consistently applied across all queries.
> Tests and audit of query option `table`

- package.json
- src/filters.js
- src/where.js
- test/connected.where.spec.js
- test/offline.filters.spec.js
- test/offline.where.spec.js
If someone used a where filter on an attribute that used "field" it would target the attributes "name" and not the stored "field".
> Where clause was not using the attributes "field" property. 

- package-lock.json
- package.json
- src/clauses.js
- src/entity.js
- src/filters.js
- src/where.js
- test/connected.page.spec.js
- test/offline.entity.spec.js
- test/offline.filters.spec.js
- test/offline.where.spec.js
This change improves query error handling to throw exceptions only when a finisher method is called. Currently some errors will throw while building the query which can result in requiring users to double up on their exception handling in the event they are using `go` or `page` which should `reject` not `throw`
> Query exception handling to originate only when `finisher` methods are called (`go`, `params`, `page`)

- www/src/pages/en/mutations/update.mdx
As per title, the basic example for `update` uses `patch` instead.
> fix: use update method in update.mdx example

- src/entity.js
- src/util.js
- test/ts_connected.crud.spec.ts
When trying to run `upsert` command, it errors if passing in a boolean attribute that is 'required' and is set to `false`. It seemed that the dynamo command created includes the attribute in `ExpressionAttributeNames` but did not pass through the value correctly into the `ExpressionAttributeValues` object, it instead sets it to `undefined`. This causes the following error to be thrown by the document client
```
ElectroError: Pass options.removeUndefinedValues=true to remove undefined values from map/array/set. - For more detail on this error reference: https://github.com/tywalch/electrodb#aws-error
```
I think I hunted down where the bug came from, it seems it was due to the following line short circuiting on the value of `upsertAttributes[field]` which was fine in most cases, except for …
> Upsert Can't handle required 'false' boolean values

- www/src/pages/en/examples/shopping-mall-directory.mdx
- www/src/partials/entity-query-example-setup.mdx
A few errors exist if you put the shopping mall example into the playground. I **only** fixed the `typos` so that playground wouldn't throw errors. I updated the access pattern keywords based on indexes of the example setup.
However, semantically queries don't make sense. I believe you wanted to use `mallId` in [example setup index](https://github.com/tywalch/electrodb/blob/44853b3ba453715b6eaddd7e6378d0eae40499f9/www/src/partials/entity-query-example-setup.mdx#L152C39-L152C39) and then queries make sense but since it is used in many places I didn't want to touch it. 
I think this is the **most well-thought** library for dynamodb I have seen in years. Good work!
> Fix Example: Errors on shopping mall example

- www/src/pages/en/mutations/batch-put.mdx
- www/src/pages/en/mutations/create.mdx
- www/src/pages/en/mutations/upsert.mdx
- www/src/pages/en/queries/find.mdx
- www/src/pages/en/queries/match.mdx
- www/src/pages/en/queries/query.mdx
- www/src/partials/entity-query-example-setup.mdx
> Doc fixes: Replace gis with gsi

- CHANGELOG.md
- package.json
- src/entity.js
- test.sh
- test/offline.entity.spec.js
- test/offline.where.spec.js
- test/ts_connected.entity.spec.ts
Addresses bug in "patch" and "update" methods that caused key composite attributes to be set with their attribute name not their "field" name. This would impact users who both use the `update` method to create new items and use alternative field name definitions for their composite keys. All other users would likely be silently impacted by this issue.
> Fixes issue 319

- CHANGELOG.md
- index.d.ts
- package.json
- src/entity.js
- src/service.js
- src/validations.js
- test/ts_connected.entity.spec.ts
- test/ts_connected.service.spec.ts
- www/src/pages/en/modeling/indexes.mdx
This property allows users to further isolate partition keys beyond just `service` participation. This implements an RFC that was thoughtfully put forward by [@Sam3d](https://github.com/sam3d) in [Issue #290](https://github.com/tywalch/electrodb/issues/290).
> Adds new property `namespace` to index definitions

- index.d.ts
- test/entity.test-d.ts
**Issue**
```tsx
const key = 'key';
type CustomAttributeTypeName<T> = { [key]: T };
// this is a simplified version of what EntityRecord will return for
// the union type
type T1 =
| CustomAttributeTypeName<{ prop1: string; prop2: string; }>
| CustomAttributeTypeName<{ prop1: string }>
| CustomAttributeTypeName<{ prop3: string }>;
// This doesn't work. `{ deploymentId: string; projectId: string; }` is missing from union.
// subtypes for a union items seem to get collapsed.
type T2 = T1 extends CustomAttributeTypeName<infer T> ? T : never;
// This works. underlying union types perserved.
type T3 = T1 extends infer U ? U extends CustomAttributeTypeName<infer U> ? U : never : never;
```
without the outer unboxing of the union type (the outer `infer`), TS collapses some of the underlying …
> Fix custom attribute type extraction for union types

- index.d.ts
- test/entity.test-d.ts
**Issue**
Same issue as #334 but for the `EntityItem` type. Copied description below:
```tsx
const key = 'key';
type CustomAttributeTypeName<T> = { [key]: T };
// this is a simplified version of what EntityItem will return for
// the union type
type T1 =
| CustomAttributeTypeName<{ prop1: string; prop2: string; }>
| CustomAttributeTypeName<{ prop1: string }>
| CustomAttributeTypeName<{ prop3: string }>;
// This doesn't work. `{ deploymentId: string; projectId: string; }` is missing from union.
// subtypes for a union items seem to get collapsed.
type T2 = T1 extends CustomAttributeTypeName<infer T> ? T : never;
// This works. underlying union types perserved.
type T3 = T1 extends infer U ? U extends CustomAttributeTypeName<infer U> ? U : never : never;
```
without the outer unboxing of …
> Fix custom attribute type extraction for union types with RecordItem

- www/src/pages/en/mutations/batch-put.mdx
The execution option to the `go` method to concurrently perform a mutation is `concurrency` and not `concurrent`.
> fix typo in batch-put.mdx

- test/ts_connected.crud.spec.ts
Test used first element in test array as heuristic to determine a list was not equal. This lead to test flake and was never really that useful.
> Fixes flakey test

- www/src/pages/en/reference/typescript.mdx
As per the index.d.ts file and in general how query responses are shaped the `QueryResponse` type is correctly typed as:
```
export type QueryResponse<E extends Entity<any, any, any, any>> = {
data: EntityItem<E>[];
cursor: string | null;
};
```
though in the docs reference it was typed as:
```
export type QueryResponse<E extends Entity<any, any, any, any>> = {
data: EntityItem<E>;
cursor: string | null;
};
```
Notice the `data: EntityItem<E>[]` in the declaration file vs `data: EntityItem<E>` in the docs.
This kinda confused me and hence this docs correction.
> Fix incorrectly documented QueryResponse type in typescript.mdx

- index.d.ts
Delete method doesn't have ConditionExpression that the item being deleted exists by default.
* fix: change the data type from `Partial<T>` to `Keys | null` when `response` option is absent or undefined
* fix: make the data types nullable in all cases
* refactor: remove `O["response"] extends "all_new"` case because `O extends DeleteQueryOptions` and `DeleteQueryOptions['response']?: "default" | "none" | "all_old"` does not include `"all_new"`
> data of entity.delete().go() should be nullable

- src/operations.js
- test/connected.update.spec.js
closes https://github.com/tywalch/electrodb/issues/460
Previous behavior:
When updating an item with a map attribute, if you attempt to set multiple keys that are identical after removing non-word characters (\w), Electro will generate the same expression attribute name for both keys. This occurs even though the original keys are different, leading to conflicts in the update operation.
This PR introduces a new change that ensures that each key will generate a unique expression attribute name.
Previously the following operation
```
tasks.patch({ id: '1' }).data((attrs, ops) => {
ops.set(attrs.map['hello world'], 1)
ops.set(attrs.map['hello    world'], 1)
}).go()
```
would generate only 1 expression attribute name `#helloworld`. this also throws an error in dynamo because you are not …
> fix formatting unique expression attribute names

- CHANGELOG.md
- index.d.ts
- index.test-d.ts
- package-lock.json
- package.json
- test/queries.test-d.ts
- test/ts_connected.crud.spec.ts
closes #439
added missing TypeScript types for `attributes` when using scan/find/match methods.
also added type tests and integration tests that are all passing
> fix(#439): add missing TypeScript types for `attributes` property on scan/find/match methods

- CHANGELOG.md
- package-lock.json
- package.json
- src/schema.js
- src/util.js
I have noticed in my production environments using ElectroDB that there is sometimes over 100 ms of post-processing overhead caused by ElectroDB. This occurs when fetching 1MB of data from DynamoDB for an entity with dozens of attributes, nested objects, arrays etc. 
After examining the source code, I discovered a couple of interesting things:
After querying DynamoDB, ElectroDB formats the items before returning them to the user. This formatting includes calling the `removeFixings` function on every attribute, which removes certain prefixes and postfixes. The function previously used string concatenation; this PR replaces it with the `.slice(start, end)` method. This change immediately halved the post-processing time.
After querying DynamoDB, ElectroDB formats the items before returning …
> Reduce ElectroDB pre/post-processing overhead before/after DynamoDB requests by up to 85%

- src/errors.js
- test/connected.batch.spec.js
- test/connected.crud.spec.js
- test/connected.page.spec.js
- test/connected.update.spec.js
- test/conversions.json
- test/offline.entity.spec.js
- test/ts_connected.crud.spec.ts
- test/ts_connected.entity.spec.ts
- test/ts_connected.update.spec.ts
Looks like a big pull request but all I did was search and replace:
`incomplete-composite-attributes`
with
`missing-composite-attributes`
It turns out to be a lot of test cases updates.
> fix: broken link in error (missing-composite-attributes)

- www/src/pages/en/modeling/indexes.mdx
Corrects a mention of `pk` to `sk` where I think it might be a typo that could be confusing.
Before:
After:
> Docs: Fix relevant typo on Modeling/Indexes page

- examples/common/client.ts
- src/clauses.js
- test/connected.batch.spec.js
- test/connected.crud.spec.js
- test/connected.filters.spec.js
- test/connected.issues.spec.js
- test/connected.issues.spec.ts
- test/connected.page.spec.js
- test/connected.service.spec.js
- test/connected.update.spec.js
- test/connected.where.spec.js
- test/init.js
- test/offline.service.spec.js
- test/offline.util.spec.js
- test/ts_connected.client.spec.ts
- test/ts_connected.complex.spec.ts
- test/ts_connected.crud.spec.ts
- test/ts_connected.entity.spec.ts
- test/ts_connected.hydration.spec.ts
- test/ts_connected.logger.spec.ts
- test/ts_connected.service.spec.ts
- test/ts_connected.transaction.spec.ts
- test/ts_connected.update.spec.ts
- test/ts_connected.validations.spec.ts
- test/ts_connected.where.spec.ts
fixes #343 
- Introduced a new test file for Issue #343 to validate upsert functionality without duplicating attribute references.
- Added credentials (accessKeyId and secretAccessKey) to the DocumentClient configuration across multiple test files and examples.
- Updated endpoint handling to use a default value of "http://localhost:8000" if LOCAL_DYNAMO_ENDPOINT is not defined.
- Refactored setFields handling in clauses.js to improve key management during upsert operations.
> fix: introduces fix for Issue #343
